apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bankoffer-prod

resources:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: prod

images:
  - name: ghcr.io/ptx37/bankoffer-api
    newTag: v1.0.0
  - name: ghcr.io/ptx37/bankoffer-worker
    newTag: v1.0.0
  - name: ghcr.io/ptx37/bankoffer-frontend
    newTag: v1.0.0

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: not-important
      spec:
        replicas: 4
        template:
          spec:
            containers:
              - name: "*"
                resources:
                  limits:
                    cpu: "2"
                    memory: 4Gi
                  requests:
                    cpu: 500m
                    memory: 2Gi

configMapGenerator:
  - name: bankoffer-kafka-config
    behavior: merge
    literals:
      - bootstrap-servers=prod-kafka.bankoffer-prod.svc.cluster.local:9094
