apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bankoffer

resources:
  - namespace.yaml

commonLabels:
  app.kubernetes.io/part-of: bankoffer

configMapGenerator:
  - name: bankoffer-kafka-config
    literals:
      - bootstrap-servers=PLACEHOLDER
      - topics=bank.transactions,offer.events,notification.events
