from __future__ import annotations

from typing import Any

PRODUCT_CATALOG: list[dict[str, Any]] = [
    {
        "product_id": "etf_starter",
        "product_name": "ETF Starter Portfolio",
        "category": "Investments",
        "description": "A diversified ETF portfolio designed for first-time investors seeking moderate growth with manageable risk.",
        "channel": "in-app",
        "priority": 2,
        "lifecycle_stage": "growth",
        "when_to_recommend": "Customer has idle cash or consistent monthly savings and is not yet investing.",
        "eligibility_criteria": {
            "min_age": 18,
            "min_income": 3000,
        },
        "suitability_criteria": {
            "min_savings": 5000,
            "min_monthly_savings": 300,
            "max_debt_to_income": 1.0,
        },
        "trigger_signals": [
            "idle_cash_high",
            "salary_increase",
            "investment_gap",
            "monthly_savings_consistent",
        ],
        "financial_health_required": ["healthy", "watchlist"],
        "investor_readiness_required": ["high", "medium"],
        "risk_bucket": "moderate",
        "recommended_channel": "in-app",
    },
    {
        "product_id": "etf_growth",
        "product_name": "ETF Growth Portfolio",
        "category": "Investments",
        "description": "An aggressive ETF portfolio targeting high returns for experienced investors with strong financial health.",
        "channel": "in-app",
        "priority": 3,
        "lifecycle_stage": "growth",
        "when_to_recommend": "High-income customer with significant savings and a high risk appetite.",
        "eligibility_criteria": {
            "min_income": 5000,
        },
        "suitability_criteria": {
            "min_savings": 10000,
            "min_monthly_savings": 500,
            "required_risk_profile": "high",
        },
        "trigger_signals": [
            "high_income",
            "bonus_event",
        ],
        "financial_health_required": ["healthy"],
        "investor_readiness_required": ["high"],
        "risk_bucket": "high",
        "recommended_channel": "in-app",
    },
    {
        "product_id": "mutual_funds",
        "product_name": "Mutual Funds",
        "category": "Investments",
        "description": "Professionally managed diversified mutual funds suitable for conservative to moderate investors.",
        "channel": "email",
        "priority": 2,
        "lifecycle_stage": "growth",
        "when_to_recommend": "Customer has savings and moderate spending behavior, seeking hands-off investment.",
        "eligibility_criteria": {},
        "suitability_criteria": {
            "min_savings": 5000,
            "behavior": "moderate",
        },
        "trigger_signals": [
            "idle_cash_high",
            "salary_increase",
            "investment_gap",
            "monthly_savings_consistent",
        ],
        "financial_health_required": ["healthy", "watchlist"],
        "investor_readiness_required": ["high", "medium"],
        "risk_bucket": ["low", "moderate"],
        "recommended_channel": "email",
    },
    {
        "product_id": "managed_portfolio",
        "product_name": "Managed Portfolio",
        "category": "Investments",
        "description": "A bespoke actively managed portfolio for high-net-worth customers seeking personalised investment strategies.",
        "channel": "email",
        "priority": 4,
        "lifecycle_stage": "wealth",
        "when_to_recommend": "High-income customer with substantial savings who wants expert portfolio management.",
        "eligibility_criteria": {
            "min_income": 8000,
        },
        "suitability_criteria": {
            "min_savings": 20000,
        },
        "trigger_signals": [
            "high_income",
            "investment_gap",
            "bonus_event",
        ],
        "financial_health_required": ["healthy"],
        "investor_readiness_required": ["high"],
        "risk_bucket": ["moderate", "high"],
        "recommended_channel": "email",
    },
    {
        "product_id": "state_bonds",
        "product_name": "State Bonds / Treasury Bills",
        "category": "Savings",
        "description": "Government-backed fixed-income instruments offering capital preservation with predictable returns.",
        "channel": "email",
        "priority": 1,
        "lifecycle_stage": "preservation",
        "when_to_recommend": "Risk-averse customer with idle cash seeking safe and stable returns.",
        "eligibility_criteria": {},
        "suitability_criteria": {
            "required_risk_profile": "low",
            "min_savings": 5000,
        },
        "trigger_signals": [
            "idle_cash_high",
        ],
        "financial_health_required": ["healthy", "watchlist"],
        "investor_readiness_required": ["high", "medium", "low"],
        "risk_bucket": "low",
        "recommended_channel": "email",
    },
    {
        "product_id": "savings_deposit",
        "product_name": "Savings Deposit",
        "category": "Savings",
        "description": "A high-interest term savings deposit account with flexible tenors and guaranteed returns.",
        "channel": "push",
        "priority": 1,
        "lifecycle_stage": "foundation",
        "when_to_recommend": "Customer with idle cash who wants a low-risk savings vehicle.",
        "eligibility_criteria": {},
        "suitability_criteria": {
            "min_savings": 3000,
        },
        "trigger_signals": [
            "idle_cash_high",
        ],
        "financial_health_required": ["healthy", "watchlist", "fragile"],
        "investor_readiness_required": ["high", "medium", "low"],
        "risk_bucket": "low",
        "recommended_channel": "push",
    },
    {
        "product_id": "private_pension",
        "product_name": "Private Pension",
        "category": "Retirement",
        "description": "A tax-advantaged private pension plan to supplement state retirement benefits.",
        "channel": "email",
        "priority": 2,
        "lifecycle_stage": "retirement_planning",
        "when_to_recommend": "Customer with consistent monthly savings who is planning for retirement.",
        "eligibility_criteria": {},
        "suitability_criteria": {
            "min_monthly_savings": 500,
        },
        "trigger_signals": [
            "monthly_savings_consistent",
            "salary_increase",
        ],
        "financial_health_required": ["healthy", "watchlist"],
        "investor_readiness_required": ["high", "medium"],
        "risk_bucket": ["low", "moderate"],
        "recommended_channel": "email",
    },
    {
        "product_id": "personal_loan",
        "product_name": "Personal Loan",
        "category": "Lending",
        "description": "A flexible unsecured personal loan with competitive rates for qualifying customers.",
        "channel": "push",
        "priority": 2,
        "lifecycle_stage": "credit_access",
        "when_to_recommend": "Customer with sufficient income needing liquidity for a specific purpose.",
        "eligibility_criteria": {
            "min_income": 3000,
        },
        "suitability_criteria": {},
        "trigger_signals": [],
        "financial_health_required": ["healthy", "watchlist"],
        "investor_readiness_required": ["high", "medium", "low"],
        "risk_bucket": ["low", "moderate"],
        "recommended_channel": "push",
    },
    {
        "product_id": "mortgage",
        "product_name": "Mortgage",
        "category": "Lending",
        "description": "Competitive fixed and variable rate mortgage products for first-time buyers and remortgagers.",
        "channel": "email",
        "priority": 3,
        "lifecycle_stage": "home_ownership",
        "when_to_recommend": "Renting customer with high income who can afford homeownership or receives a bonus.",
        "eligibility_criteria": {
            "min_income": 6000,
            "no_existing_mortgage": True,
        },
        "suitability_criteria": {},
        "trigger_signals": [
            "rent_pattern",
            "bonus_event",
            "high_income",
        ],
        "financial_health_required": ["healthy"],
        "investor_readiness_required": ["high", "medium"],
        "risk_bucket": ["low", "moderate"],
        "recommended_channel": "email",
    },
    {
        "product_id": "credit_card",
        "product_name": "Credit Card",
        "category": "Cards",
        "description": "Rewards and cashback credit card with tailored limits and benefits for active spenders.",
        "channel": "push",
        "priority": 2,
        "lifecycle_stage": "everyday_banking",
        "when_to_recommend": "Customer with high transaction volume or strong shopping patterns.",
        "eligibility_criteria": {
            "min_income": 2500,
        },
        "suitability_criteria": {},
        "trigger_signals": [
            "shopping_pattern",
        ],
        "financial_health_required": ["healthy", "watchlist"],
        "investor_readiness_required": ["high", "medium", "low"],
        "risk_bucket": ["low", "moderate"],
        "recommended_channel": "push",
    },
    {
        "product_id": "life_insurance",
        "product_name": "Life Insurance",
        "category": "Insurance",
        "description": "Term and whole-life insurance products providing financial protection for families.",
        "channel": "email",
        "priority": 2,
        "lifecycle_stage": "protection",
        "when_to_recommend": "Customer who is married or has dependents who rely on their income.",
        "eligibility_criteria": {},
        "suitability_criteria": {
            "min_dependents": 1,
            "or_married": True,
        },
        "trigger_signals": [
            "family_context",
        ],
        "financial_health_required": ["healthy", "watchlist"],
        "investor_readiness_required": ["high", "medium", "low"],
        "risk_bucket": ["low", "moderate"],
        "recommended_channel": "email",
    },
    {
        "product_id": "travel_insurance",
        "product_name": "Travel Insurance",
        "category": "Insurance",
        "description": "Comprehensive single-trip and annual multi-trip travel insurance for frequent travellers.",
        "channel": "push",
        "priority": 1,
        "lifecycle_stage": "lifestyle",
        "when_to_recommend": "Customer shows a spike in travel-related spending.",
        "eligibility_criteria": {},
        "suitability_criteria": {},
        "trigger_signals": [
            "travel_spike",
        ],
        "financial_health_required": ["healthy", "watchlist", "fragile"],
        "investor_readiness_required": ["high", "medium", "low"],
        "risk_bucket": ["low", "moderate", "high"],
        "recommended_channel": "push",
    },
]

PRODUCT_MAP: dict[str, dict[str, Any]] = {p["product_id"]: p for p in PRODUCT_CATALOG}
