apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bankoffer-staging

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

images:
  - name: ghcr.io/ptx37/bankoffer-api
    newTag: staging-latest
  - name: ghcr.io/ptx37/bankoffer-worker
    newTag: staging-latest
  - name: ghcr.io/ptx37/bankoffer-frontend
    newTag: staging-latest

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: not-important
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: "*"
                resources:
                  limits:
                    cpu: "1"
                    memory: 1Gi
                  requests:
                    cpu: 250m
                    memory: 512Mi

configMapGenerator:
  - name: bankoffer-kafka-config
    behavior: merge
    literals:
      - bootstrap-servers=staging-kafka.bankoffer-staging.svc.cluster.local:9094
